"""
Data Models for Standalone Viral Video Clipping Pipeline
========================================================
Consolidated data structures for 100% self-contained execution inside /clipping.
"""

from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class ClipSourceType(str, Enum):
    LOCAL_FILE = "local_file"
    YOUTUBE = "youtube"
    LIVESTREAM = "livestream"
    DIRECT_URL = "direct_url"


class VisualAssessment(BaseModel):
    """Visual evaluation generated by Google LiteRT-LM Gemma 4 E2B running on phone."""
    visual_hook_score: float = Field(..., description="Visual retention hook score out of 10")
    facial_expression: str = Field(..., description="Scene description / facial kinetics generated by Gemma 4 E2B")
    face_crop_center_x: float = Field(default=50.0, description="Recommended 9:16 vertical crop center percentage (0-100%)")
    active_speaker_identified: bool = Field(default=True, description="Whether active subject/speaker was detected")
    visual_hook_summary: str = Field(..., description="Summary of visual virality potential")
    keyframe_timestamp: Optional[float] = Field(default=None, description="Timestamp in seconds where frame was sampled")
    scene_title: Optional[str] = Field(default=None, description="Gemma 4 E2B scene title")
    model_latency_ms: Optional[float] = Field(default=None, description="Inference latency on Snapdragon 8 Elite GPU")


class SlidingWindowResult(BaseModel):
    """Result of temporal sliding window evaluation."""
    window_id: str
    start_seconds: float
    end_seconds: float
    frames_count: int
    peak_visual_timestamp: float
    peak_visual_score: float
    speaker_center_x: float = 50.0
    summary: str


class ViralClipItem(BaseModel):
    """Ranked viral clip recommendation."""
    clip_id: str
    rank: int
    start_time: str
    end_time: str
    start_seconds: float
    end_seconds: float
    duration_seconds: float
    virality_score: int
    hook_line: str
    why_viral: str
    suggested_title: str
    suggested_caption: str
    hashtags: List[str]
    transcript_snippet: Optional[str] = None
    visual_assessment: Optional[VisualAssessment] = None
    recommended_aspect_ratio: str = "9:16"
    exported_video_path: Optional[str] = None


class ClipAnalysisRequest(BaseModel):
    """Input parameters for video clipping."""
    video_url: str
    creator_name: Optional[str] = None
    target_duration_seconds: int = 45
    min_virality_score: int = 70
    max_clips: int = 3
    use_on_device_gemma: bool = True
    enable_sliding_window: bool = True
    window_size_seconds: int = 120
    frame_interval_seconds: int = 3
    export_mp4: bool = False
    phone_endpoint: str = "http://localhost:8080"


class ClipAnalysisResponse(BaseModel):
    """Full response containing all top viral clips and performance metrics."""
    status: str = "success"
    video_title: str
    video_duration: str
    source_type: str
    signals_used: List[str]
    on_device_model: str
    hardware_target: str = "iQOO 15 (Snapdragon 8 Elite Adreno GPU)"
    sliding_windows_analyzed: int
    total_frames_processed: int
    total_candidates_analyzed: int
    top_viral_clips: List[ViralClipItem]
